-- 1. Initialize Extensions
CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;

-- 2. OLTP Tables (Relational Schema)

CREATE TABLE IF NOT EXISTS app_users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(150) NOT NULL,
    password character varying(128) NOT NULL,
    role character varying(10) NOT NULL DEFAULT 'USER',
    last_login timestamp(6) with time zone,
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_app_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS brands (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name character varying(30) NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (id),
    CONSTRAINT uk_brand_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name character varying(255) NOT NULL,
    public_id uuid NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT uk_category_name UNIQUE (name),
    CONSTRAINT uk_category_public_id UNIQUE (public_id)
);

CREATE TABLE IF NOT EXISTS product (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_url text,
    price numeric(12,2),
    product_url text,
    public_id uuid NOT NULL,
    tier character varying(255) NOT NULL,
    title text,
    brand_id bigint NOT NULL,
    -- ADDED GENDER TO SOURCE TABLE
    gender character(1) NOT NULL, 
    color text,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT uk_product_public_id UNIQUE (public_id),
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id)
        REFERENCES brands (id) ON UPDATE CASCADE ON DELETE CASCADE,
    -- Constraints for data integrity
    CONSTRAINT product_tier_check CHECK (tier::text = ANY (ARRAY['BUDGET'::text, 'MID'::text, 'PREMIUM'::text])),
    CONSTRAINT product_gender_check CHECK (gender = ANY (ARRAY['F'::text, 'M'::text, 'U'::text]))
);

CREATE TABLE IF NOT EXISTS product_categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT uk_product_category UNIQUE (product_id, category_id),
    CONSTRAINT fk_prodcat_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_prodcat_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

-- 3. Search-Optimized Projection Table (Read Layer)

CREATE TABLE IF NOT EXISTS product_search (
    product_id bigint PRIMARY KEY,
    embedding vector(1536), 
    brand_id bigint,
    brand_name text,
    tier varchar(20),
    price numeric(12,2),
    category_ids bigint[], 
    gender character(1), -- Now correlates directly with product.gender
    color text,
    CONSTRAINT fk_search_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

-- 4. Indices & Vector Optimization

-- DISKANN INDEX
CREATE INDEX idx_product_search_diskann ON product_search
USING diskann (embedding vector_cosine_ops)
WITH (storage_layout = 'memory_optimized');

-- GIN Index for category array filtering
CREATE INDEX idx_product_search_cat_gin ON product_search USING gin (category_ids);

-- B-Tree index for tiered and gender filtering (High selectivity)
CREATE INDEX idx_product_search_tier ON product_search (tier);
CREATE INDEX idx_product_search_gender ON product_search (gender);
CREATE INDEX idx_product_search_brand_id ON product_search (brand_id);

-- 5. Missing / Recommended Performance Indexes
CREATE INDEX IF NOT EXISTS idx_product_brand_id_fk ON product (brand_id);
CREATE INDEX IF NOT EXISTS idx_product_created_at ON product (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_search_price_tier ON product_search (tier, price);

-- 6. Maintenance Tuning
ALTER SYSTEM SET maintenance_work_mem = '2GB';
ALTER SYSTEM SET max_parallel_maintenance_workers = 4;
